apply plugin: 'com.android.application'

android {
    compileSdkVersion 33
    buildToolsVersion '36.0.0'
    namespace = "com.example.daniel.fitlog"

    defaultConfig {
        applicationId "com.example.daniel"
        minSdkVersion 33
        targetSdkVersion 35
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }
    compileOptions {
        targetCompatibility 21
        sourceCompatibility 21
    }
}

dependencies {
    implementation 'com.android.support.constraint:constraint-layout:2.0.4'
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support:support-v4:28.0.0'
    implementation 'com.android.support:support-compat:28.0.0'
    implementation 'com.android.support:design:28.0.0'
    implementation 'com.jjoe64:graphview:4.2.1'
}
